### ISSUE TITLE
Openshift Support?

### ISSUE THREAD

**Issue by jkroepke** [tinselspoon/intellij-kubernetes#1]
Hi!

Openshift is a on top kubernetes product. It adds some resources like Routes, BuildConfig, e.g.

Here is REST documentation: https://docs.openshift.org/latest/rest_api/openshift_v1.html

**Comment by tinselspoon** [comment]
Thanks for the suggestion! I haven't used OpenShift myself but it looks like they provide a swagger format for the API in a very similar style to Kubernetes, so this shouldn't be too hard to get working.

I just need to get some automated tests into the plugin and then I'll start work on this.

**Comment by jkroepke** [comment]
Maybe its possible to parse the offical documentatiom to generate the autocomplete here instead maintain it manually.

**Comment by tinselspoon** [comment]
Version 0.4 of the plugin adds OpenShift support. You'll need to enable it in Settings > Languages and Frameworks > Kubernetes and OpenShift. Please let me know if you have any problems.

**Comment by jkroepke** [comment]
Wow, that was fast!

**Comment by tinselspoon** [comment]
Luckily it was quite easy to add in!
