### ISSUE TITLE
Add support for kubernetes 1.6

### ISSUE THREAD

**Issue by prog110** [tinselspoon/intellij-kubernetes#2]
Kubernetes 1.6 is just out. Can u update the plugin to support the latest release

**Comment by tinselspoon** [comment]
I've added the 1.6 API definitions to the plugin, version 0.5. Once you update it should be used as the default for completion unless you've changed the version in the settings page.

Please let me know if you encounter any issues with the new definitions.

**Comment by prog110** [comment]
Sorry for the delay responding. I have tested with the latest version of plugin.

Though the latest apiVersion for StatefulSet is `apps/v1beta1`, the plugin sets this value to `apps/v1alpha1`

Please verify

**Comment by tinselspoon** [comment]
Thanks, yes I see that too. It looks like for some reason the Swagger specs define the StatefulSet under both `apps/v1alpha1` and `apps/v1beta1` (https://github.com/kubernetes/kubernetes/blob/release-1.6/api/swagger-spec/apps_v1alpha1.json and https://github.com/kubernetes/kubernetes/blob/release-1.6/api/swagger-spec/apps_v1beta1.json) and the plugin just picks the first one when suggesting the `apiVersion` initially.

I'll open up a new issue to address this. Thanks for reporting.
