### ISSUE TITLE
Wrong apiVersion suggested for StatefulSet (and potentially others)

### ISSUE THREAD

**Issue by tinselspoon** [tinselspoon/intellij-kubernetes#3]
Swagger specs define the StatefulSet under both `apps/v1alpha1` and `apps/v1beta1` (https://github.com/kubernetes/kubernetes/blob/release-1.6/api/swagger-spec/apps_v1alpha1.json and https://github.com/kubernetes/kubernetes/blob/release-1.6/api/swagger-spec/apps_v1beta1.json) and the plugin just picks the first one when suggesting the `apiVersion` initially.

We should find a way to preference the later versions when suggesting the `apiVersion`.

See comment in #2

**Comment by tinselspoon** [comment]
The new version 0.6 now uses some hopefully sensible logic to put the latest available `apiVersion` when suggesting a `kind`. @thekalinga hope this addresses your issue.

**Comment by prog110** [comment]
Thanks. I have verified this for statefulset.

How about the property validation in yaml. Does the validation also be done using this latest version for teh whole document (i.e if I place a property from `apps/v1alpha1` in this `apps/v1beta1`, would the validator throw an error or not)?

**Comment by tinselspoon** [comment]
Yes, it uses the specific `kind` and `apiVersion` you give for completion and validation. So if a new property was added in `v1beta1`, you wouldn't see it in the completion if the apiVersion was set to `v1alpha1`.

The autocompletion of `apiVersion` when you first add a `kind` is only a suggestion, you're free to change it and it will use the corresponding set of definitions.

**Comment by prog110** [comment]
Thanks
