### ISSUE TITLE
Enable support for Gogland

### ISSUE THREAD

**Issue by dlsniper** [tinselspoon/intellij-kubernetes#4]
Hi,

Thank you for the work on the plugin.
Could you please enable Gogland support in the plugin page? According to this: https://youtrack.jetbrains.com/issue/GO-4280#comment=27-2355975 that's something that can be resolved only on your side.
Thank you.

**Comment by tinselspoon** [comment]
Thanks for your interest in the plugin!

I would like to enable it for Gogland but I was initially unable to as it depends on the IntelliJ YAML plugin which was bundled with IntelliJ IDEA, but not Gogland. However, it looks like the YAML plugin is now included in Gogland so this should no longer be an issue.

I do have an EAP of Gogland, but I'm not sure if I've messed up my configuration of it while testing, so please could you verify the following for me?
1. When editing a YAML file, do you see syntax highlighting of keys and values?
2. In File -> Settings -> Plugins, is "YAML" listed as a plugin, similar to the screenshot below?

![image](https://user-images.githubusercontent.com/9112859/29091708-b86f1172-7c7b-11e7-9030-1b622db1f557.png)

If the above is true in Gogland, there shouldn't be any issue enabling support.

Thanks!

**Comment by dlsniper** [comment]
Hi @tinselspoon, I can confirm that I can do all of those actions. Furthermore, I can confirm that the plugin can be installed manually in the IDE. Hope it helps. Thank you for all your efforts on this and for the super speedy reply.

**Comment by tinselspoon** [comment]
Awesome, thanks for confirming - I've enabled compatibility for Gogland.

**Comment by dlsniper** [comment]
<3 thank you!
