### ISSUE TITLE
Question - Where should I found the OpenShift integration plugin?

### ISSUE THREAD

**Issue by rakeshnambiar** [tinselspoon/intellij-kubernetes#5]
Where should I found the OpenShift integration plugin which is mentioned below?

https://www.jetbrains.com/help/idea/run-debug-configuration-openshift-deployment.html

**Comment by tinselspoon** [comment]
It looks like that page is describing a different plugin - this one only provides autocompletion etc for the yaml files - there isn't any deploy/build functionality.

[This page](https://www.jetbrains.com/help/idea/working-with-cloud-platforms.html) says:
> There is a separate cloud integration plugin for each of the supported cloud platforms. All the cloud integration plugins are bundled with the IDE and enabled by default.

Which would suggest that the plugin should already be installed. It could be an IntelliJ Ultimate-only feature - I only have the community edition and can't see it (or a way of obtaining it).

Maybe get in touch with JetBrains support for a definitive answer?

**Comment by rakeshnambiar** [comment]
Thanks for your reply. 
I too arrives the same conclusion.
