### ISSUE TITLE
More than 2 objects in a file produce errors

### ISSUE THREAD

**Issue by ClemLivy** [tinselspoon/intellij-kubernetes#8]
First of all, thanks this plugin! It is very convenient!

As it is mentioned in kubernetes best practice, it s good to group related objects in a single file separated by `---`. It works perfectly for two objects, but if I implement a third one, then the plugin see this as an error:

> Duplicated property
<img width="317" alt="screen shot 2018-01-26 at 10 45 56 am" src="https://user-images.githubusercontent.com/24570966/35434110-35386ce0-0286-11e8-9d77-06501e559c60.png">

references:
https://kubernetes.io/docs/concepts/configuration/overview/#general-config-tips
https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml

**Comment by tinselspoon** [comment]
Hi, thanks for reporting this!

I'm having trouble reproducing this with the file you've linked - when I open it I don't see any errors. Would you be able to share the exact file you were using?

Could you also verify there is no leading or trailing whitespace around the `---` in your file (i.e. ensure the dashes are the only characters on the line)? This may stop IntelliJ recognising it as separate documents.

**Comment by ClemLivy** [comment]
Well, I moved the object to the top of my file and no more error... then I put it down again and no more errors. Like you, I am enable to reproduce it... Probably not an issue finally.
